# ref: https://docs.travis-ci.com/user/languages/python
language: python

services:
  - docker

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

before_install:
  - docker-compose up -d --build

install:
  - pip install -r requirements.txt
  - pip install tox

script:
  - tox
